require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegistersController do

  # This should return the minimal set of attributes required to create a valid
  # Register. As you add validations to Register, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Descripcion" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegistersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registers as @registers" do
      register = Register.create! valid_attributes
      get :index, {}, valid_session
      assigns(:registers).should eq([register])
    end
  end

  describe "GET show" do
    it "assigns the requested register as @register" do
      register = Register.create! valid_attributes
      get :show, {:id => register.to_param}, valid_session
      assigns(:register).should eq(register)
    end
  end

  describe "GET new" do
    it "assigns a new register as @register" do
      get :new, {}, valid_session
      assigns(:register).should be_a_new(Register)
    end
  end

  describe "GET edit" do
    it "assigns the requested register as @register" do
      register = Register.create! valid_attributes
      get :edit, {:id => register.to_param}, valid_session
      assigns(:register).should eq(register)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Register" do
        expect {
          post :create, {:register => valid_attributes}, valid_session
        }.to change(Register, :count).by(1)
      end

      it "assigns a newly created register as @register" do
        post :create, {:register => valid_attributes}, valid_session
        assigns(:register).should be_a(Register)
        assigns(:register).should be_persisted
      end

      it "redirects to the created register" do
        post :create, {:register => valid_attributes}, valid_session
        response.should redirect_to(Register.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved register as @register" do
        # Trigger the behavior that occurs when invalid params are submitted
        Register.any_instance.stub(:save).and_return(false)
        post :create, {:register => { "Descripcion" => "invalid value" }}, valid_session
        assigns(:register).should be_a_new(Register)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Register.any_instance.stub(:save).and_return(false)
        post :create, {:register => { "Descripcion" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested register" do
        register = Register.create! valid_attributes
        # Assuming there are no other registers in the database, this
        # specifies that the Register created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Register.any_instance.should_receive(:update).with({ "Descripcion" => "MyString" })
        put :update, {:id => register.to_param, :register => { "Descripcion" => "MyString" }}, valid_session
      end

      it "assigns the requested register as @register" do
        register = Register.create! valid_attributes
        put :update, {:id => register.to_param, :register => valid_attributes}, valid_session
        assigns(:register).should eq(register)
      end

      it "redirects to the register" do
        register = Register.create! valid_attributes
        put :update, {:id => register.to_param, :register => valid_attributes}, valid_session
        response.should redirect_to(register)
      end
    end

    describe "with invalid params" do
      it "assigns the register as @register" do
        register = Register.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Register.any_instance.stub(:save).and_return(false)
        put :update, {:id => register.to_param, :register => { "Descripcion" => "invalid value" }}, valid_session
        assigns(:register).should eq(register)
      end

      it "re-renders the 'edit' template" do
        register = Register.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Register.any_instance.stub(:save).and_return(false)
        put :update, {:id => register.to_param, :register => { "Descripcion" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested register" do
      register = Register.create! valid_attributes
      expect {
        delete :destroy, {:id => register.to_param}, valid_session
      }.to change(Register, :count).by(-1)
    end

    it "redirects to the registers list" do
      register = Register.create! valid_attributes
      delete :destroy, {:id => register.to_param}, valid_session
      response.should redirect_to(registers_url)
    end
  end

end
